### ISSUE TITLE
World crash on load

### ISSUE THREAD

**Issue by funnycubeguy** [SrRapero720/dimthreads#3]
Running the all the mods 9 pack. Any ideas?

`---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2024-01-23 13:45:46
Description: Exception ticking world

java.lang.IllegalStateException: EntitiesLoadEvent cannot be triggered asynchronously from another thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:581) ~[forge-1.20.1-47.2.20-universal.jar%23995!/:?] {re:classloading}
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntitiesLoadEvent(CraftEventFactory.java:1788) ~[forge-1.20.1-47.2.20-universal.jar%23995!/:?] {re:classloading}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157582_(PersistentEntitySectionManager.java:295) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157506_(PersistentEntitySectionManager.java:302) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:438) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:libx:level_load,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:corgilib.mixins.json:MixinServerLevel,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:ars_elemental.mixins.json:ServerLevelMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:hyperbox.mixins.json:ServerLevelMixin,pl:mixin:APP:aether.mixins.json:common.accessor.ServerLevelAccessor,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.md626043$lambda$tickWorlds$0$5(MinecraftServer.java:5758) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:gtceu.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:dimthread.mixin.json:MinecraftServerMixin,pl:mixin:A}
	at me.srrapero720.dimthread.DimThread.swapThreadsAndRun(DimThread.java:39) ~[dimthread-1.20.1-v1.0.0.jar%23698!/:1.0.0] {re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.md626043$lambda$tickWorlds$1$4(MinecraftServer.java:5755) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:gtceu.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:dimthread.mixin.json:MinecraftServerMixin,pl:mixin:A}
	at me.srrapero720.dimthread.thread.ThreadPool.lambda$execute$1(ThreadPool.java:52) ~[dimthread-1.20.1-v1.0.0.jar%23698!/:1.0.0] {re:mixin,re:classloading}
	at me.srrapero720.dimthread.thread.ThreadPool.lambda$execute$0(ThreadPool.java:44) ~[dimthread-1.20.1-v1.0.0.jar%23698!/:1.0.0] {re:mixin,re:classloading}
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?] {}
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?] {}
	at java.lang.Thread.run(Thread.java:840) [?:?] {re:mixin}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Suspected Mod: 
	Dimensional Threading Reforked (dimthread), Version: 1.0.0
		Mixin class: me.srrapero720.dimthread.mixin.MinecraftServerMixin
		Target: net.minecraft.server.MinecraftServer
		at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.md626043$lambda$tickWorlds$0$5(MinecraftServer.java:5758)
Stacktrace:
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:581) ~[forge-1.20.1-47.2.20-universal.jar%23995!/:?] {re:classloading}
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntitiesLoadEvent(CraftEventFactory.java:1788) ~[forge-1.20.1-47.2.20-universal.jar%23995!/:?] {re:classloading}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157582_(PersistentEntitySectionManager.java:295) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157506_(PersistentEntitySectionManager.java:302) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:438) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:libx:level_load,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:corgilib.mixins.json:MixinServerLevel,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:ars_elemental.mixins.json:ServerLevelMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:hyperbox.mixins.json:ServerLevelMixin,pl:mixin:APP:aether.mixins.json:common.accessor.ServerLevelAccessor,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins,pl:mixin:A}
-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 2209
	Level dimension: ad_astra:earth_orbit
	Derived: true
	Level spawn location: World: (0,107,0), Section: (at 0,11,0 in 0,6,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 36831 game time, 36831 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 28874 (now: false), thunder time: 46371 (now: false)
	Known server brands: mohist
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at me.srrapero720.dimthread.util.CrashInfo.crash(CrashInfo.java:11) ~[dimthread-1.20.1-v1.0.0.jar%23698!/:1.0.0] {re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.handler$cja000$tickWorlds(MinecraftServer.java:5769) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:gtceu.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:dimthread.mixin.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1148) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:gtceu.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:dimthread.mixin.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:341) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithostitched.mixins.json:server.DedicatedServerMixin,pl:mixin:APP:mixins/common/nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1074) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:gtceu.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:dimthread.mixin.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:904) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:gtceu.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:dimthread.mixin.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:gtceu.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:dimthread.mixin.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:840) [?:?] {re:mixin}

`

**Comment by funnycubeguy** [comment]
`[13:52:25 ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
        at me.srrapero720.dimthread.util.CrashInfo.crash(CrashInfo.java:12) ~[dimthread-1.20.1-v1.0.0.jar%23698!/:1.0.0]
        at net.minecraft.server.MinecraftServer.handler$cja000$tickWorlds(MinecraftServer.java:5769) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1148) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:341) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1074) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:904) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.IllegalStateException: EntitiesLoadEvent cannot be triggered asynchronously from another thread.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:581) ~[forge-1.20.1-47.2.20-universal.jar%23995!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntitiesLoadEvent(CraftEventFactory.java:1788) ~[forge-1.20.1-47.2.20-universal.jar%23995!/:?]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157582_(PersistentEntitySectionManager.java:295) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157506_(PersistentEntitySectionManager.java:302) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?]
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:438) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?]
        at net.minecraft.server.MinecraftServer.mda32ec0$lambda$tickWorlds$0$5(MinecraftServer.java:5758) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?]
        at me.srrapero720.dimthread.DimThread.swapThreadsAndRun(DimThread.java:39) ~[dimthread-1.20.1-v1.0.0.jar%23698!/:1.0.0]
        at net.minecraft.server.MinecraftServer.mda32ec0$lambda$tickWorlds$1$4(MinecraftServer.java:5755) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?]
        at me.srrapero720.dimthread.thread.ThreadPool.lambda$execute$1(ThreadPool.java:52) ~[dimthread-1.20.1-v1.0.0.jar%23698!/:1.0.0]
        at me.srrapero720.dimthread.thread.ThreadPool.lambda$execute$0(ThreadPool.java:44) ~[dimthread-1.20.1-v1.0.0.jar%23698!/:1.0.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        ... 1 more
[13:52:25 ERROR]:       Cause of unexpected exception was
java.lang.IllegalStateException: EntitiesLoadEvent cannot be triggered asynchronously from another thread.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:581) ~[forge-1.20.1-47.2.20-universal.jar%23995!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntitiesLoadEvent(CraftEventFactory.java:1788) ~[forge-1.20.1-47.2.20-universal.jar%23995!/:?]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157582_(PersistentEntitySectionManager.java:295) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157506_(PersistentEntitySectionManager.java:302) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?]
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:438) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?]
        at net.minecraft.server.MinecraftServer.mda32ec0$lambda$tickWorlds$0$5(MinecraftServer.java:5758) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?]
        at me.srrapero720.dimthread.DimThread.swapThreadsAndRun(DimThread.java:39) ~[dimthread-1.20.1-v1.0.0.jar%23698!/:1.0.0]
        at net.minecraft.server.MinecraftServer.mda32ec0$lambda$tickWorlds$1$4(MinecraftServer.java:5755) ~[server-1.20.1-20230612.114412-srg.jar%23990!/:?]
        at me.srrapero720.dimthread.thread.ThreadPool.lambda$execute$1(ThreadPool.java:52) ~[dimthread-1.20.1-v1.0.0.jar%23698!/:1.0.0]
        at me.srrapero720.dimthread.thread.ThreadPool.lambda$execute$0(ThreadPool.java:44) ~[dimthread-1.20.1-v1.0.0.jar%23698!/:1.0.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
[13:52:25 FATAL]: Preparing crash report with UUID 2a8fdeeb-46a0-40f1-b46e-cecb79f91a76`

**Comment by SrRapero720** [comment]
Won't... Try to run a very sensitive mod on a hybrid server, the first thing appear on your crash report is "bukkit.

Remove dimensional threading if you really need plugins in your server. Otherwise use pure forge...
