### ISSUE TITLE
[Incompatibility] Hard incompatibility with Petrolpark's Library (Create: Destroy)

### ISSUE THREAD

**Issue by splat1125** [SrRapero720/dimthreads#30]
Running Dimthread with Petrolpark's Library causes it to spit out this message and overfill the console. Executing any command causes the server to freeze after executing the command.

I'm aware the modpack is extremely large, though the issue seems clear-cut — it cites Petrolpark's decayingitemhandler as the thing being caught as an exception, thus causing fatal issues.

```
[19Nov2024 20:13:59.039] [dimthread_server_overworld/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: class com.petrolpark.itemdecay.DecayingItemHandler$1 cannot be cast to class com.petrolpark.itemdecay.DecayingItemHandler$ServerDecayingItemHandler (com.petrolpark.itemdecay.DecayingItemHandler$1 and com.petrolpark.itemdecay.DecayingItemHandler$ServerDecayingItemHandler are in module petrolpark@1.0.6 of loader 'TRANSFORMER' @29188050)
	Index: 10
	Listeners:
		0: HIGH
		1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		2: NORMAL
		3: net.minecraftforge.eventbus.EventBus$$Lambda/0x000001d6297fcd08@9ad9a40
		4: net.minecraftforge.eventbus.EventBus$$Lambda/0x000001d6297fcd08@6e56cea1
		5: net.minecraftforge.eventbus.EventBus$$Lambda/0x000001d6297fcd08@1feafa6b
		6: ASM: class com.aetherteam.aether.event.listeners.DimensionListener onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		7: ASM: com.mrcrayfish.framework.event.ForgeEvents@1ffd2f9a onLevelTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		8: ASM: com.teamabnormals.blueprint.common.capability.chunkloading.ChunkLoaderEvents@55f70156 tickChunkLoader(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		9: ASM: class net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge onServerTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		10: ASM: class com.petrolpark.PetrolparkCommonEvents onTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		11: net.minecraftforge.eventbus.EventBus$$Lambda/0x000001d6297fcd08@6e1ce8fb
		12: net.minecraftforge.eventbus.EventBus$$Lambda/0x000001d6297fcd08@b0610e2
		13: ASM: class com.petrolpark.destroy.events.DestroyCommonEvents onTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		14: ASM: class com.simibubi.create.foundation.events.CommonEvents onServerWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		15: ASM: class com.railwayteam.railways.forge.events.CommonEventsForge onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		16: ASM: com.illusivesoulworks.polymorph.common.CommonEventsListener@789f892 levelTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		17: ASM: com.natamus.collective.forge.events.RegisterCollectiveForgeEvents@304a591f onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
java.lang.ClassCastException: class com.petrolpark.itemdecay.DecayingItemHandler$1 cannot be cast to class com.petrolpark.itemdecay.DecayingItemHandler$ServerDecayingItemHandler (com.petrolpark.itemdecay.DecayingItemHandler$1 and com.petrolpark.itemdecay.DecayingItemHandler$ServerDecayingItemHandler are in module petrolpark@1.0.6 of loader 'TRANSFORMER' @29188050)
	at TRANSFORMER/petrolpark@1.0.6/com.petrolpark.PetrolparkCommonEvents.onTick(PetrolparkCommonEvents.java:54)
	at TRANSFORMER/petrolpark@1.0.6/com.petrolpark.__PetrolparkCommonEvents_onTick_LevelTickEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.3.0/net.minecraftforge.event.ForgeEventFactory.onPostLevelTick(ForgeEventFactory.java:930)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.mdcefda6$dimthread$lambda$tickWorlds$0$7(MinecraftServer.java:6398)
	at TRANSFORMER/dimthread@1.0.5/me.srrapero720.dimthread.DimThread.swapThreadsAndRun(DimThread.java:50)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.mdcefda6$dimthread$lambda$tickWorlds$1$6(MinecraftServer.java:6391)
	at TRANSFORMER/dimthread@1.0.5/me.srrapero720.dimthread.thread.ThreadPool.lambda$execute$1(ThreadPool.java:54)
	at TRANSFORMER/dimthread@1.0.5/me.srrapero720.dimthread.thread.ThreadPool.lambda$execute$0(ThreadPool.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by splat1125** [comment]
I should add that this is using the 1.20.1 build of dimthread! v1.0.5.

**Comment by SrRapero720** [comment]
can you please fill the full logs instead of a crash-report snipped? thanks
and that crash doesn't seems to be caused by dimthreads
